# Regenerates references/catalog.md from the actual SKILL.md frontmatter on disk.
# Run after installing, removing, or renaming skills:
#   powershell -NoProfile -File "$env:USERPROFILE\.claude\skills\skill-router\scripts\build-catalog.ps1"
# ASCII-only on purpose: Windows PowerShell 5.1 reads this file as ANSI.

$ErrorActionPreference = 'Stop'
$root = Join-Path $env:USERPROFILE '.claude\skills'
$out  = Join-Path $root 'skill-router\references\catalog.md'
$bt   = [char]96   # backtick, for markdown inline code

function Get-Frontmatter($path) {
    $lines = Get-Content -LiteralPath $path -Encoding UTF8
    if ($lines.Count -lt 2 -or $lines[0].Trim() -ne '---') { return $null }
    $desc = $null; $inDesc = $false
    for ($i = 1; $i -lt $lines.Count; $i++) {
        $l = $lines[$i]
        if ($l.Trim() -eq '---') { break }
        if ($l -match '^description:\s*(.*)$') { $desc = $Matches[1].Trim(); $inDesc = $true; continue }
        if ($inDesc -and $l -match '^\s+\S')   { $desc = $desc + ' ' + $l.Trim(); continue }
        $inDesc = $false
    }
    if (-not $desc) { return $null }
    ($desc.Trim(' ', '"', "'") -replace '\s+', ' ' -replace '\|', '/')
}

$rows = Get-ChildItem $root -Directory | ForEach-Object {
    $s = Join-Path $_.FullName 'SKILL.md'
    if (-not (Test-Path $s)) { return }
    $d = Get-Frontmatter $s
    if (-not $d) { return }
    [pscustomobject]@{ Dir = $_.Name; Description = $d }
} | Sort-Object Dir

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Personal skill catalog')
$lines.Add('')
$lines.Add('Generated by scripts/build-catalog.ps1 from ~/.claude/skills/*/SKILL.md.')
$lines.Add('The files on disk are the source of truth - regenerate instead of editing this by hand.')
$lines.Add('')
$lines.Add(('Count: **{0}** skills. Last generated: {1}.' -f $rows.Count, (Get-Date -Format 'yyyy-MM-dd')))
$lines.Add('')
$lines.Add('| Skill | What it is for |')
$lines.Add('|---|---|')
foreach ($r in $rows) {
    $d = $r.Description
    if ($d.Length -gt 220) { $d = $d.Substring(0, 217) + '...' }
    $lines.Add(('| {0}{1}{0} | {2} |' -f $bt, $r.Dir, $d))
}

New-Item -ItemType Directory -Force (Split-Path $out) | Out-Null
[System.IO.File]::WriteAllLines($out, $lines, (New-Object System.Text.UTF8Encoding $false))
Write-Output ('Wrote {0} skills to {1}' -f $rows.Count, $out)
